### ISSUE TITLE
Help with updating our ferguson transcript converter

### ISSUE THREAD

**Issue by ondrae** [ondrae/ferguson-grand-jury-transcripts#3]
#### Description

Currently `txt2an.py` is expecting text files like `files/VOLUME I.txt` to convert them to Akoma Ntoso like `files/VOLUME I.an`.

It needs to be rewritten to expect the new [text format](https://github.com/ondrae/ferguson-grand-jury-transcripts/blob/master/files/pdfminer/output/ferguson_grand_jury_testimony.txt). This new format will help us better handle redacted names and the varying formats of the Q&A sections.

The Q&A sections sometimes have the questioners name, sometimes a Q, and sometimes a crazy indent.
#### Tasks
- [x] Create separate debate sections for each VOLUME such as 

```
<debateSection>
    <heading>VOLUME I</heading>
    ...
</debateSection>
```
- [ ] Better handling for redacted names
- [x] Fine tuning of the Q&A formatting
