### ISSUE TITLE
Add witness name where we know it

### ISSUE THREAD

**Issue by ondrae** [ondrae/ferguson-grand-jury-transcripts#8]
In Volume IV, we know the person being interviewed is DORIAN JOHNSON.
We should changed the A to his name in that section.

Any other known witnesses? For each, we need to check, that they are the only person being interviewed in that section.

#### Files
volume.py

#### Tasks
- [ ] Make new function called `replace_known_names()`
- [ ] add `<TLCPerson href="/ontology/person/ferguson.sayit.mysociety.org/dorian-johnson" id="dorian-johnson" showAs="Dorian Johnson"/>` to the references element.
- [ ] have it replace all the `#a` speeches with `#dorian-johnson`
